### ISSUE TITLE
PlexConnect ipa's to .deb's?

### ISSUE THREAD

**Issue by wahlmanj** [Diatrus/diatrus.github.io#2]
Any chance you could add these to your repo? The first one is the official one, the second is a very nice theme as are the remaining two.

https://github.com/iBaa/PlexConnectApp
https://github.com/CyberGhost84/PlexConnectApp
https://github.com/falco953/PlexConnectApp
https://github.com/pecinko/PlexConnectApp

**Comment by Diatrus** [comment]
I'll add soon.

**Comment by wahlmanj** [comment]
There is but this is more feature rich as in the cover-art views for shows/movies when browsing.

**Comment by Diatrus** [comment]
Added and tested. Working on 11.3 as far as I can see. Tell your friends and keep makin requests haha @wahlmanj

**Comment by wahlmanj** [comment]
Any chance you could also add the Cyberghost version also, the other two I can live without. Tested on 11.1 and it works using the iBaa version, thank you for this!

**Comment by wahlmanj** [comment]
Lots more tvOS apps here:

http://www.idownloadblog.com/2015/11/07/find-apps-tvos-ios-sideload-github/

Thank you so much for adding this, I forgot you can switch between themes just using Ghosts theme.

**Comment by Diatrus** [comment]
That is the cyberghost version. I made iBaa the author because he made it originally.
